- hosts: localhost
  vars:
    ansible_python_interpreter: "/Users/stefanalexandruromila/Library/Application\ Support/pipx/venvs/ansible/bin/python"
  tasks:
    - import_tasks: tasks/zsh.yml
    - import_tasks: tasks/node.yml
    - import_tasks: tasks/npm-packages.yml
    - import_tasks: tasks/dotfiles.yml
    - import_tasks: tasks/brew-packages.yml
    - import_tasks: tasks/nvim.yml
    - import_tasks: tasks/git.yml
