- hosts: localhost
  become: true
  vars:
    ansible_python_interpreter: "\"/Users/stefanalexandruromila/Library/Application Support/pipx/venvs/ansible/bin/python\""
  pre_tasks:
    - name: Install Homebrew
      shell: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      args:
        creates: /usr/local/bin/brew
    - name: Update Homebrew cache
      homebrew:
        update_cache: yes
      tags:
        - install
  tasks:
    - include: tasks/zsh.yml
    - include: tasks/node.yml
    - include: tasks/npm-packages.yml
    - include: tasks/productivity-tools.yml
    - include: tasks/dotfiles.yml
    - include: tasks/nvim.yml
