- hosts: localhost
  vars:
    ansible_python_interpreter: "\"/Users/stefanalexandruromila/Library/Application Support/pipx/venvs/ansible/bin/python\""
  tasks:
    - include: tasks/zsh.yml
    - include: tasks/node.yml
    - include: tasks/npm-packages.yml
    - include: tasks/dotfiles.yml
    - include: tasks/nvim.yml
