- name: Install packages using Homebrew
  homebrew:
    name:
      - tmux
      - fzf
      - lua
      - luajit
      - ripgrep
      - tree-sitter
    state: present
  tags:
    - homebrew

- name: Install iTerm2 using Homebrew Cask
  homebrew_cask:
    name: iterm2
    state: present
  tags:
    - homebrew
  ignore_errors: yes

- name: Install fzf key bindings and fuzzy completion
  command: "{{ lookup('env', 'HOMEBREW_PREFIX') }}/opt/fzf/install --all"
  args:
    creates: "{{ lookup('env', 'HOMEBREW_PREFIX') }}/opt/fzf/shell/key-bindings.zsh"
  tags:
    - homebrew
