- name: Install packages using Homebrew
  homebrew:
    name:
      - tmux
      - fzf
      - lua
      - luajit
      - ripgrep
      - tree-sitter
      - n
    state: present
  tags:
    - homebrew

- name: Install fzf key bindings and fuzzy completion
  command: "{{ ansible_env.HOMEBREW_PREFIX }}/opt/fzf/install --key-bindings --completion --no-update-rc"
  args:
    creates: "{{ ansible_env.HOMEBREW_PREFIX }}/opt/fzf/shell/key-bindings.zsh"
  tags:
    - homebrew
