- name: Install Homebrew (if not already installed)
  command: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
  args:
    creates: /opt/homebrew/bin/brew
  tags:
    - homebrew

- name: Install packages using Homebrew
  homebrew:
    name:
      - tmux
      - fzf
      - lua
      - luajit
      - ripgrep 
      - tree-sitter
    state: present
  tags:
    - homebrew

- name: Install iTerm2 using Homebrew Cask
  homebrew_cask:
    name: iterm2
    state: present
  tags:
    - homebrew
