---
- name: Install packages and applications with Homebrew on Apple Silicon
  hosts: localhost
  become: yes  # Allows Ansible to run commands with sudo (as needed)

  tasks:
    - name: Install Homebrew (if not already installed)
      command: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
      args:
        creates: /opt/homebrew/bin/brew
      when: ansible_architecture == "arm64"  # Apple Silicon-specific installation

    - name: Install packages using Homebrew
      ansible.builtin.homebrew:
        name:
          - tmux
          - fzf
          - lua
          - luajit
        state: present
      when: ansible_architecture == "arm64"  # Apple Silicon-specific package installation

    - name: Install iTerm2 using Homebrew Cask
      ansible.builtin.homebrew_cask:
        name: iterm2
        state: present
      when: ansible_architecture == "arm64"  # Apple Silicon-specific application installation
  tags:
    - homebrew

