---
- name: Install Node.js and npm
  ansible.builtin.command: brew install node
  tags:
    - node

- name: Install n using npm
  ansible.builtin.npm:
    name: n
    global: yes
  tags:
    - node

- name: Install Node.js version 20 using n
  ansible.builtin.command: n 20
  tags:
    - node
