- name: Install Node.js and npm
  ansible.builtin.command: brew install node
  tags:
    - node

- name: Install bun
  ansible.builtin.command: curl -fsSL https://bun.sh/install
  args:
    executable: /bin/zsh
  tags:
    - node
    - bun
