- name: Install Neovim via Homebrew
  homebrew:
    name: neovim
    state: present
  tags:
    - install
    - nvim

- name: Ensure Neovim packer directory exists
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/.local/share/nvim/site/pack/packer/start"
    state: directory
  tags:
    - install
    - neovim

- name: Clone Packer.nvim if not already cloned
  ansible.builtin.shell: git clone --depth 1 https://github.com/wbthomason/packer.nvim ~/.local/share/nvim/site/pack/packer/start/packer.nvim
  args:
    executable: /bin/zsh  
  tags:
    - install
    - neovim

