- name: Ensure Neovim plugin directories exist
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/.config/nvim/pack/packer/start"
    state: directory
  tags:
    - install
    - neovim

- name: Get Packer
  ansible.builtin.git:
    repo: 'https://github.com/wbthomason/packer.nvim'
    dest: "{{ lookup('env', 'HOME') }}/.config/nvim/pack/packer/start/packer.nvim"
  tags:
    - install
    - neovim
- name: Install Neovim 
  apt: 
  name: neovim 
  tags:
    - install
    - nvim  

