---
- name: Ensure Neovim plugin directories exist
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/.config/nvim/pack/packer/start"
    state: directory
  tags:
    - install
    - neovim

- name: Clone Packer.nvim if not already cloned
  ansible.builtin.git:
    repo: 'https://github.com/wbthomason/packer.nvim'
    dest: ~/.local/share/nvim/site/pack/packer/start/packer.nvim
  tags:
    - install
    - neovim

- name: Install Neovim
  homebrew:
    name: neovim
    state: present
  tags:
    - install
    - nvim
