- name: Install Neovim via Homebrew
  homebrew:
    name: neovim
    state: present
  tags:
    - install
    - nvim

- name: Clone Packer.nvim
  git:
    repo: 'https://github.com/wbthomason/packer.nvim'
    dest: '~/.local/share/nvim/site/pack/packer/start/packer.nvim'
    version: 'master'
  tags:
    - install
    - nvim
