- name: Install Neovim via Homebrew
  homebrew:
    name: neovim
    state: present
  tags:
    - install
    - nvim
- name: Ensure Neovim packer directory exists
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/.local/share/nvim/site/pack/packer/start"
    state: directory
  tags:
    - install
    - neovim

- name: Clone Packer.nvim if not already cloned
  ansible.builtin.git:
    repo: 'https://github.com/wbthomason/packer.nvim'
    dest: "{{ lookup('env', 'HOME') }}/.local/share/nvim/site/pack/packer/start/packer.nvim"
    depth: 1
  tags:
    - install
    - neovim

