---
- name: Ensure Neovim plugin directories exist
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/.config/nvim/pack/packer/start"
    state: directory
  tags:
    - install
    - neovim

- name: Clone Packer.nvim if not already cloned
  ansible.builtin.git:
    repo: 'https://github.com/wbthomason/packer.nvim'
    dest: "{{ lookup('env', 'HOME') }}/.config/nvim/pack/packer/start/packer.nvim"
  tags:
    - install
    - neovim

- name: Check if Packer.nvim is installed
  ansible.builtin.stat:
    path: "{{ lookup('env', 'HOME') }}/.config/nvim/pack/packer/start/packer.nvim/packer.lua"
  register: packer_installed
  tags:
    - install
    - neovim

- name: Install Neovim
  homebrew:
    name: neovim
    state: present
  when: packer_installed.stat.exists == false
  tags:
    - install
    - nvim
