- name: Install Zsh
  homebrew:
    name: zsh
    state: present
  become: false
  tags: zsh

- name: Add Homebrew Zsh to /etc/shells
  lineinfile:
    path: /etc/shells
    line: '/opt/homebrew/bin/zsh'
    create: no
  become: true
  tags: zsh

- name: Change shell to Zsh
  ansible.builtin.shell: chsh -s $(which zsh)
  become: false
  tags: zsh

- name: Install Oh-My-Zsh
  shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  args:
    creates: "~/.oh-my-zsh"
  become: false
  tags: zsh

- name: Ensure .oh-my-zsh custom plugin directory exists
  file:
    path: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
    state: directory
  become_user: "{{ ansible_env.USER }}"
  tags: zsh

- name: Install the zsh-autosuggestions plugin
  git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
  become_user: "{{ ansible_env.USER }}"
  tags: zsh

- name: Update .zshrc to enable zsh-autosuggestions
  lineinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    regexp: '^plugins='
    line: 'plugins=(git zsh-autosuggestions)'
    backrefs: yes
  become_user: "{{ ansible_env.USER }}"
  tags: zsh
