---
- name: Install Zsh
  ansible.builtin.command: brew install zsh
  tags:
    - zsh

- name: Change shell to Zsh
  ansible.builtin.shell: chsh -s $(which zsh)
  args:
    executable: /bin/zsh
  tags:
    - zsh

- name: Install Oh-My-Zsh
  ansible.builtin.shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  tags:
    - zsh

- name: Install the zsh-autosuggestions plugin
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
    dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
  tags:
    - zsh

- name: Update .zshrc to enable zsh-autosuggestions
  ansible.builtin.lineinfile:
    path: ~/.zshrc
    insertbefore: EOF
    line: 'plugins=(git zsh-autosuggestions)'
  tags:
    - zsh
